# Generated by Django 3.1 on 2020-09-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
